logs:
  build: ./logs
  ports:
    - "3006:3006"
  environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=logsdb
  depends_on:
    - db_logs
db_logs:
  image: postgres
  restart: always
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: logsdb
  ports:
    - "5433:5432"
