apiVersion: apps/v1
kind: Deployment
metadata:
  name: barramento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barramento
  template:
    metadata:
      labels:
        app: barramento
    spec:
      containers:
        - name: barramento-container
          image: enrico/barramento:latest
          ports:
            - containerPort: 3000