apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consulta
  template:
    metadata:
      labels:
        app: consulta
    spec:
      containers:
        - name: consulta-container
          image: enrico/consulta:latest
          ports:
            - containerPort: 3000
          env:
            - name: BARRAMENTO_URL
              value: "http://barramento:3000"
