apiVersion: apps/v1
kind: Deployment
metadata:
  name: lembretes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lembretes
  template:
    metadata:
      labels:
        app: lembretes
    spec:
      containers:
        - name: lembretes-container
          image: enrico/lembretes:latest
          ports:
            - containerPort: 3000
          env:
            - name: BARRAMENTO_URL
              value: "http://barramento:3000"
