apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
        - name: logs-container
          image: enrico/logs:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "mongodb://logs-db:27017/logs"
